/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MessageBoard } from "./MessageBoard";
import { MessageBoardCountArgs } from "./MessageBoardCountArgs";
import { MessageBoardFindManyArgs } from "./MessageBoardFindManyArgs";
import { MessageBoardFindUniqueArgs } from "./MessageBoardFindUniqueArgs";
import { DeleteMessageBoardArgs } from "./DeleteMessageBoardArgs";
import { MessageBoardService } from "../messageBoard.service";
@graphql.Resolver(() => MessageBoard)
export class MessageBoardResolverBase {
  constructor(protected readonly service: MessageBoardService) {}

  async _messageBoardsMeta(
    @graphql.Args() args: MessageBoardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MessageBoard])
  async messageBoards(
    @graphql.Args() args: MessageBoardFindManyArgs
  ): Promise<MessageBoard[]> {
    return this.service.messageBoards(args);
  }

  @graphql.Query(() => MessageBoard, { nullable: true })
  async messageBoard(
    @graphql.Args() args: MessageBoardFindUniqueArgs
  ): Promise<MessageBoard | null> {
    const result = await this.service.messageBoard(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MessageBoard)
  async deleteMessageBoard(
    @graphql.Args() args: DeleteMessageBoardArgs
  ): Promise<MessageBoard | null> {
    try {
      return await this.service.deleteMessageBoard(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
